name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
        # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### meta
          API_BASE_URL: https://wakatime.com/api 
          REPOSITORY: Otto-Samuel/Otto-Samuel 
          ### content
          SHOW_TITLE: true 
          SECTION_NAME: waka 
          BLOCKS: -> 
          CODE_LANG: rust 
          TIME_RANGE: all_time 
          LANG_COUNT: 10 
          SHOW_TIME: true 
          SHOW_TOTAL: true 
          SHOW_MASKED_TIME: false 
          STOP_AT_OTHER: true 
          IGNORED_LANGUAGES: YAML JSON TOML 
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics 
          TARGET_BRANCH: master 
          TARGET_PATH: README.md 
          COMMITTER_NAME: GitHubActionBot 
          COMMITTER_EMAIL: action-bot@github.com 
          AUTHOR_NAME: Otto-Samuel
          AUTHOR_EMAIL: ottosamuel01@gmail.com 
